services:
    redis:
    image: redis:7.2-alpine
    restart: always
    user: root
    env_file:
      - .env
    ports:
      - $REDIS_PORT:$REDIS_PORT
    command: sh -c "redis-server --requirepass $REDIS_PASSWORD --port $REDIS_PORT"
    privileged: true
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 10
    volumes:
      - ./docker/data/redis:/data